### ISSUE TITLE
Deleting foods

### ISSUE THREAD

**Issue by katiekeel** [katiekeel/quantified-self#8]
When I click the "Delete" icon next to a food, it will be removed from the list.

**Comment by thedanielvogelsang** [comment]
I call it!

**Comment by thedanielvogelsang** [comment]
This is passing technically. But I dont think we should close this issue until we successfully are deleting via ajax call. My thought is that might mean we need to make a separate call to any tables where Food can't be deleted due to associations.

**Comment by katiekeel** [comment]
Can now delete foods from database as long as they don't belong to a meal.
